  [build]
  publish = "public"
  command = "hugo --gc --minify -b $URL"

[context.production.environment]
  HUGO_VERSION = "0.125.0" # Change to your desired Hugo version

  [build.environment]
  PHP_VERSION = "8.3"

