[build]
  publish = "public"
  command = "hugo --gc --minify -b $URL"

  [build.environment]
    HUGO_VERSION = "0.125.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    NODE_VERSION = "18"
    PHP_VERSION = "8.3"
