---
title: "Data Communication"
author: "MACSS 30500 <br /> University of Chicago"
output:
  xaringan::moon_reader:
    css: ["../cfss.css"]
    nature:
      highlightStyle: magula
      highlightLines: true
      highlightLanguage: r
      ratio: 16:9
      countIncrementalSlides: false
---

```{r setup, include = FALSE}
# generate CSS file
library(xaringanthemer)

#source(here::here("R", "slide-opts.R"))

# enable panelsets and default theme
xaringanExtra::use_panelset()
```

```{r pkgs, include = FALSE, cache = FALSE}
library(tidyverse)
library(palmerpenguins)
library(c3s2)
library(knitr)
library(patchwork)
library(flipbookr)

set.seed(1234)
theme_set(theme_gray(base_size = 16))
```

# Agenda

* Review layers + EDA
* Communicating with Data
  * Labels
  * Annotations
  * Scales
  * Themes
  * Layout
  

---
class: inverse, middle

# Communicating with data

---

## Labels

---
## Annotataions

---
## Scales

---
## Themes

---
## Layout

---
# Recap:

* Labels
* Annotations
* Scales
* Themes
* Layout
  
